apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}
  labels:
    app:{{ .Values.application.name }}
    chart: {{ .Values.application.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"

