apiVersion: v1
kind: Service
metadata:
  name: az-helm-aks
  labels:
    app: az-helm-aks
    chart: az-helm-aks
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30007
      protocol: TCP
      name: http
  selector:
    app: az-helm-aks
    release: {{ .Release.Name }}
