apiVersion: v1
kind: Service
metadata:
  name: az-helm-aks
  labels:
    app: {{ .Values.Application.Name }}
    chart: {{ .Values.Application.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.Application.Name }}
    release: {{ .Release.Name }}
